### ISSUE TITLE
WSGI

### ISSUE THREAD

**Issue by bravo321** [zveronline/docker-sopds#19]
а возможно настроить что бы это работало через wsgi?
то есть, у меня это выглядело так :
```
<VirtualHost *:8001>
    ServerAdmin bravo.123@localhost
    DocumentRoot "/opt/sopds"
    ServerName sopds-apache
    ServerAlias sopds-apache.local
    ErrorLog "/var/log/httpd/sopds-apach.local-error_log"
    CustomLog "/var/log/httpd/sopds-apache.local-access_log" common
   WSGIApplicationGroup %{GLOBAL}
   WSGIScriptAlias / /opt/sopds/sopds/wsgi.py
   WSGIDaemonProcess sopds processes=3 threads=15 python-path=/opt/sopds/
   WSGIProcessGroup sopds
   WSGIScriptReloading On
   WSGIPassAuthorization On

   <Directory "/opt/sopds/sopds/">
      Require all granted
   </Directory>

   <Directory "/opt/sopds/static/">
      Require all granted
   </Directory>

   Alias   /static    "/opt/sopds/static"


</VirtualHost>


```
а как это настроить с докером мне не понятно ..

**Comment by zveronline** [comment]
Я честно говоря в этом не особо понимаю, даже сам апач почти не использовал. А чем плохо просто проксировать?

**Comment by bravo321** [comment]
Я в этом вообще ни чего не понимаю :) , просто у меня стоял sopds настроенный, а тут python обновился до 3.11 и всё поломалось, вот разбираюсь как это дело восстановить, и реши попробовать докер .. там у меня были некоторые свои изменения в интерфейсе, конвертерах, вот и пытаюсь понять как это сделать проще :)

**Comment by zveronline** [comment]
у sopds есть свой вебсервер, на питоне же и написанный, мне даже в голову не приходило выполнять код напрямую через апач, для этого нужно было бы этот апач впихнуть в этот же контейнер, это долго, нудно и не понятно зачем.
у докер конейнера на его ip на порту 8001 в http висит работающий sopds, порт можно дополнительно повесить на ip хоста для удобства

**Comment by bravo321** [comment]
Запускаю командой

**Comment by bravo321** [comment]
О, запустил:

**Comment by zveronline** [comment]
> Запускаю командой `docker run --name sopds -d --volume /run/media/HTPC_Data/MyLibs/LibRusEc:/library:ro --volume /var/lib/postgres:/var/lib/pgsql --publish 8081:8001 zveronline/sopds` он запускается но после этого только сыплет логами :
> 
> ```
> docker logs sopds
> pg_ctl: could not open PID file "/var/lib/pgsql/data/postmaster.pid": Permission denied
> Mon May  8 19:25:48 MSK 2023 - waiting for database to start
> Mon May  8 19:25:58 MSK 2023 - waiting for database to start
> Mon May  8 19:26:08 MSK 2023 - waiting for database to start
> Mon May  8 19:26:18 MSK 2023 - waiting for database to start
> Mon May  8 19:26:28 MSK 2023 - waiting for database to start
> Mon May  8 19:26:38 MSK 2023 - waiting for database to start
> Mon May  8 19:26:48 MSK 2023 - waiting for database to start
> Mon May  8 19:26:58 MSK 2023 - waiting for database to start
> Mon May  8 19:27:08 MSK 2023 - waiting for database to start
> Mon May  8 19:27:18 MSK 2023 - waiting for database to start
> Mon May  8 19:27:28 MSK 2023 - waiting for database to start
> Mon May  8 19:27:38 MSK 2023 - waiting for database to start
> Mon May  8 19:27:48 MSK 2023 - waiting for database to start
> Mon May  8 19:27:58 MSK 2023 - waiting for database to start
> Mon May  8 19:28:08 MSK 2023 - waiting for database to start
> Mon May  8 19:28:18 MSK 2023 - waiting for database to start
> Mon May  8 19:28:28 MSK 2023 - waiting for database to start
> Mon May  8 19:28:38 MSK 2023 - waiting for database to start
> Mon May  8 19:28:48 MSK 2023 - waiting for database to start
> ```

Этот вариант лучше, база не потеряется, но явно вылезла какая-то проблема с правами
