### ISSUE TITLE
By default, sqlite is used, not postresql

### ISSUE THREAD

**Issue by MasterHome** [zveronline/docker-sopds#22]
Hi! I'm used this image in TrueNas Scale. By default, sqlite is used, not postresql. You need to replace copy path for settings.py in docker file: "COPY configs/settings.py ." replace with "COPY configs/settings.py ./sopds"
ЗЫ. Извини за кривой английский :)

**Comment by MasterHome** [comment]
Просто добавил перенос файла "&& mv settings.py ./sopds/settings.py \"

**Comment by zveronline** [comment]
я несколько раз перепроверил, файл был на месте и переносится он нормально

**Comment by MasterHome** [comment]
Т.е. у тебя сейчас settings.py после запуска образа лежит только в /sopds/sopds или дополнительно есть и в /sopds? 
WORKDIR /sopds всё верно, только вот конфиг должен быть в /sopds/sopds

**Comment by zveronline** [comment]
действительно, я уже стал забывать как оно устроено, странно что у меня работает.

**Comment by MasterHome** [comment]
Извини, надо было мне первый пост поправить. Если оставить "COPY configs/settings.py ./sopds" на своём месте, то не соберётся. Можно эту строку оставить как есть и добавить в RUN "&& mv settings.py ./sopds/settings.py "

**Comment by zveronline** [comment]
да ломать не строить, щас понаворочу

**Comment by MasterHome** [comment]
"COPY configs/settings.py ./sopds" вернуть в исходное "COPY configs/settings.py ." иначе не соберётся.

**Comment by zveronline** [comment]
> "COPY configs/settings.py ./sopds" вернуть в исходное "COPY configs/settings.py ." иначе не соберётся.

да я уже заметил что оно мешает распаковке, забыл просто про это
