### ISSUE TITLE
/sopds folder empty after container run

### ISSUE THREAD

**Issue by prostoprojekt** [zveronline/docker-sopds#27]
Привет!
Устанавливаю docker-sopds:latest на NAS Synology - контейнер запускается, sopds-сервер запускается по указанному 8001 порту.

В созданном каталоге /sopds на сервере видны только:
--/data
--setconf

В чем может быть причина, что остальные файлы контейнера не видны в /sopds ?

Непосредственно в контейнере докера

```

~# docker exec -i -t sopds ls -alF /
total 4
drwxr-xr-x    1 root     root           174 Jun  1 11:00 ./
drwxr-xr-x    1 root     root           174 Jun  1 11:00 ../
-rwxr-xr-x    1 root     root             0 Jun  1 10:59 .dockerenv*
drwxr-xr-x    1 root     root           870 Jun  1 07:09 bin/
drwxr-xr-x    5 root     root           340 Jun  1 11:00 dev/
drwxr-xr-x    1 root     root           842 Jun  1 10:59 etc/
drwxr-xr-x    1 root     root             0 Nov 11  2022 home/
drwxr-xr-x    1 root     root           410 Feb  4 03:23 lib/
drwxr-xr-x    1 postgres postgres       962 May 30 15:07 library/
drwxr-xr-x    1 root     root            28 Nov 11  2022 media/
drwxr-xr-x    1 root     root             0 Nov 11  2022 mnt/
drwxr-xr-x    1 root     root             0 Nov 11  2022 opt/
dr-xr-xr-x  834 root     root             0 Jun  1 11:00 proc/
drwx------    1 root     root             0 Nov 11  2022 root/
drwxr-xr-x    1 root     root            20 Jun  1 11:00 run/
drwxr-xr-x    1 root     root           800 Nov 11  2022 sbin/
drwxr-xr-x    1 root     root           438 Jun  1 07:09 sopds/
drwxr-xr-x    1 root     root             0 Nov 11  2022 srv/
-rwxr-xr-x    1 root     root          1913 Jun  1 07:08 start.sh*
dr-xr-xr-x   12 root     root             0 Jun  1 11:00 sys/
drwxrwxrwt    1 root     root             0 Feb  4 03:23 tmp/
drwxr-xr-x    1 root     root            60 Jun  1 07:09 usr/
drwxr-xr-x    1 root     root            86 Feb  4 03:23 var/

```

**Comment by zveronline** [comment]
не понял вопроса
![image](https://github.com/zveronline/docker-sopds/assets/4943561/9243af22-8f0c-4d1a-81cd-408b4a607c44)

**Comment by zveronline** [comment]
лучше объясни как ты его запускаешь при том что его не видно в gui

**Comment by zveronline** [comment]
папки я бы прокинул примерно так

![image](https://github.com/zveronline/docker-sopds/assets/4943561/139263c0-53e4-4aa0-90d3-daa9f9a75668)

**Comment by prostoprojekt** [comment]
> лучше объясни как ты его запускаешь при том что его не видно в gui. в filestation видно будет только postgres, как вынести туда логи не могу подсказать.

Про filestation понятно, получается логи нужно смотреть через терминал контейнера, или  подключившись через ssh , далее в контейнер docker, в каком-то из этих каталогов ?
![242589808-9243af22-8f0c-4d1a-81cd-408b4a607c44](https://github.com/zveronline/docker-sopds/assets/10762163/d0ce80d7-53a8-4ca5-837b-e2b0ed07cbd1)

**Comment by prostoprojekt** [comment]
> лучше объясни как ты его запускаешь при том что его не видно в gui. в filestation видно будет только postgres, как вынести туда логи не могу подсказать.

Запускаю через portainer - там на удивление этот контейнер виден

![portainer](https://github.com/zveronline/docker-sopds/assets/10762163/8cb0ea6a-570e-4416-bdda-34b391ef6611)

**Comment by zveronline** [comment]
у меня ни разу не получалось запустить на synology portainer, видимо что-то допилили.
а вообще с правами на папки все сложнее чем кажется.

![image](https://github.com/zveronline/docker-sopds/assets/4943561/a7a683d9-3c8f-485e-ae57-2127c73cf540)

**Comment by zveronline** [comment]
я думаю синоложи вмешивается и меняет права папки под себя на ходу

**Comment by prostoprojekt** [comment]
> у меня ни разу не получалось запустить на synology portainer, видимо что-то допилили. а вообще с правами на папки все сложнее чем кажется.
> 
> ![image](https://user-images.githubusercontent.com/4943561/242600849-a7a683d9-3c8f-485e-ae57-2127c73cf540.png)

я создал папку вручную в docker/sopds - поставил контейнер - удалил контейнер из портейнера - папку /sopds  не удалял - поставил еще раз ... и бд туда встала

**Comment by prostoprojekt** [comment]
надо ему (mariushosting) в дискорде написать, там норм группа есть, может что подскажут как поставить правильно, чтобы виден был в докере..

**Comment by zveronline** [comment]
я сделал небольшой фикс, теперь postgres не падает
