### ISSUE TITLE
Read Online

### ISSUE THREAD

**Issue by bravo321** [zveronline/docker-sopds#29]
Не работает у меня ссылка Read Online, так как там подставляется адрес HTTPS:// а у меня он HTTP:// ну и соответственно omnireader.ru на это ругается, ну и зря из интерфейса выпилили скачивание в fb2.zip , его все читалки умеют, а трафик в разы меньше.
Пишу сюда, по тому что  на https://github.com/ichbinkirgiz/sopds , писать некуда, я так понимаю что это его исправления ..

**Comment by ichbinkirgiz** [comment]
Вернул fb2.zip. Насчёт HTTP:// буду думать.

**Comment by ichbinkirgiz** [comment]
Включил  у себя Issues. Теперь можно пинать меня напрямую.

**Comment by ichbinkirgiz** [comment]
Вроде починил переход на omnireader.ru по HTTP:// если sopds сервер не доступен по HTTPS://
@zveronline : создай новый имидж плс.
@bravo321 : напиши потом фурычит оно или нет.

**Comment by bravo321** [comment]
Да собственно я сам подправил у себя и http и fb2.zip , скачивать докер не
хочу, так как  у меня своих исправлений много, телебот тот же, да и внешний
вид немного под себя изменял ..

сб, 25 мая 2024 г. в 14:33, Kyrgyz ***@***.***>:
