### ISSUE TITLE
[Proposal] For new functionality

### ISSUE THREAD

**Issue by PeterVoronov** [zveronline/docker-sopds#8]
Hi.

Many thanks for your very useful and nice docker image.
I can propose some optimization and features:

1. ~~Reducing size of image by combining a lot of changes in one Run - please see [appropriate pull request](https://github.com/zveronline/docker-sopds/pull/4).~~ accepted.
2. Adding functionality of automatic superuser creation on startup via expect - [another pull request](https://github.com/zveronline/docker-sopds/pull/9).
3. And addint the next generation of fb2conv - [fb2converter](https://github.com/rupor-github/fb2converter) - there is [third pull request](https://github.com/zveronline/docker-sopds/pull/10).

P.S. Will not spam you more, excuse me.

**Comment by zveronline** [comment]
I just need some time to test.

**Comment by PeterVoronov** [comment]
Sure
